### ISSUE TITLE
it's not keeping the theme when show the answer

### ISSUE THREAD

**Issue by dvbeato** [sumnerevans/menu-calc#5]
I'm using this config in my i3 to start rofi, `bindsym $mod+space exec rofi -show drun -theme $HOME/.dotfiles/linux/rofi-night -show-icons` but when I made a calculation, the rofi menu that shows the calculation is not keeping my theme.

**Comment by sumnerevans** [comment]
I think that this is due to rofi not forwarding on all of the arguments to `=`.

The intent is for `=` to be used as a standalone, for example:

```
bindsym $mod+c exec = -- -theme $HOME/.dotfiles/linux/rofi-nigh -show-icons
```

You can also try setting the theme for rofi globally using the Xresources method for setting values for rofi.
